# main menu navigation
menu:
  Home: /
  About: /about
  EthFans: https://ethfans.org/
  
widgets:
  - tag
  - archive
  - recent_posts
  - category

# social config
social:
  github: btc-study/Bitcoin-ideas-Chinese-based-on-Nakamoto-Institute
  # zhihu:
  # twitter: /
  # facebook: /
  # linkedin:
  # instagram: /

user:
  name: BTC study
  avatar: /images/avatar.png
  location: In the dust
  description: May the Force be with you

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: btc-study/Bitcoin-ideas-Chinese-based-on-Nakamoto-Institute # your blog repo

# dark
# light
# user-can-set
appearance: auto # Default value is auto

highlight:
  enable: true

# Miscellaneous
favicon: /favicon.ico
