# main menu navigation
menu:
  Home: /
  About: /about
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category

# social config
social:
  zhihu:
  twitter: /
  facebook: /
  linkedin:
  instagram: /
  github: /

user:
  name: btc.study
  avatar: /images/avatar.jpg
  location: In the dust
  description: May the Force be with you

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: btc-study/Bitcoin-ideas-Chinese-based-on-Nakamoto-Institute # your blog repo

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: /images/favicon.png
highlight:
  enable: true